<?php

namespace Proxies\__CG__\Croangels\ESV\EcommerceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categorie extends \Croangels\ESV\EcommerceBundle\Entity\Categorie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'id', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'nom', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'parent', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'description', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'icone', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'articles', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'fils');
        }

        return array('__isInitialized__', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'id', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'nom', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'parent', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'description', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'icone', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'articles', '' . "\0" . 'Croangels\\ESV\\EcommerceBundle\\Entity\\Categorie' . "\0" . 'fils');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categorie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent($parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcone($icone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcone', array($icone));

        return parent::setIcone($icone);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcone', array());

        return parent::getIcone();
    }

    /**
     * {@inheritDoc}
     */
    public function addArticle(\Croangels\ESV\EcommerceBundle\Entity\Article $articles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticle', array($articles));

        return parent::addArticle($articles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticle(\Croangels\ESV\EcommerceBundle\Entity\Article $articles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticle', array($articles));

        return parent::removeArticle($articles);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticles', array());

        return parent::getArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function addFils(\Croangels\ESV\EcommerceBundle\Entity\Categorie $fils)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFils', array($fils));

        return parent::addFils($fils);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFils(\Croangels\ESV\EcommerceBundle\Entity\Categorie $fils)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFils', array($fils));

        return parent::removeFils($fils);
    }

    /**
     * {@inheritDoc}
     */
    public function getFils()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFils', array());

        return parent::getFils();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addFil(\Croangels\ESV\EcommerceBundle\Entity\Categorie $fils)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFil', array($fils));

        return parent::addFil($fils);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFil(\Croangels\ESV\EcommerceBundle\Entity\Categorie $fils)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFil', array($fils));

        return parent::removeFil($fils);
    }

}
