croangels_esv_utilisateur:
    resource: "@CroangelsESVUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /utilisateur

croangels_esv_ecommerce:
    resource: "@CroangelsESVEcommerceBundle/Resources/config/routing.yml"
    prefix:   /

## SONATA ADMIN :
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
