croangels_esv_utilisateur:
    resource: "@CroangelsESVUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /utilisateur
    options:
        expose: true


croangels_esv_ecommerce:
    resource: "@CroangelsESVEcommerceBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        expose: true


## SONATA ADMIN :
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

## FOSJSROUTING

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
