<?php

namespace Croangels\ESV\EcommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleVignetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleVignetteRepository extends EntityRepository
{
}
