<?php

namespace Croangels\ESV\EcommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends EntityRepository
{
}
